
networks:
  lp-apps:
    external: true

services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - lp-apps

volumes:
  npm_data:
  npm_letsencrypt:

#   - Email: `admin@example.com`
#   - Password: `changeme`