version: '3'
# (Optional) when using custom network
networks:
  lp-apps:
    external: False

services:
  pg-db:
    # (Recommended) replace "latest" with specific version
    image: postgres:15
    container_name: pg-db
    environment:
      - POSTGRES_USER=odoo18
      - POSTGRES_PASSWORD=odoo18
    ports:
      - "5433:5432"
    # (Optional) when using custom network
    networks:
      - lp-apps
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always


  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com # TODO change
      PGADMIN_DEFAULT_PASSWORD: postgres # TODO change
      # SCRIPT_NAME: /pgadmin4
    ports:
    - "5050:80"
    networks:
      - lp-apps  
    volumes:
    - pgadmin:/var/lib/pgadmin

volumes:
  pgadmin:
  db-data: